name = 'Janssen'
license = 'MIT'
licenselink = 'https://github.com/jwtay1/hugo-theme-janssen/LICENSE'
description = 'A Hugo documentation theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/jwtay1/hugo-theme-janssen'

# If you have a running demo of the theme
demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['blog', 'company']
features = ['some', 'awesome', 'features']

# If the theme has a single author
[author]
  name = 'Jian Wei Tay'
  homepage = 'https://jianweitay.com'