baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

theme = 'hugo-theme-janssen'
themesDir = '../..'

sectionPagesMenu = 'main'

[params]
  copyright = "Copyright &copy; 2025 This Person, Inc."

[menus]
  [[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10
  [[menus.main]]
  name = 'Features'
  pageRef = '/features'
  weight = 12

  [[menus.footer1]]
    name = 'Link 1'
    url = 'https://example.com'
    
    [menus.footer1.params]
      rel = 'external'

  [[menus.footer4]]
    name = 'Link 1'
    url = 'https://example.com'
    
    [menus.footer4.params]
      rel = 'external'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
