baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Janssen'

theme = 'hugo-theme-janssen'
themesDir = '../..'

[params]
  copyright = "Copyright &copy; 2025 This Person, Inc."
  footer1_title = "Footer 1"
  footer2_title = "Footer 2"
  footer3_title = "Footer 3"
  footer4_title = "Footer 4"

[menus]
  [[menus.main]]
  name = 'Getting started'
  pageRef = '/getting-started'
  weight = 1
  
  [[menus.main]]
  name = 'Features'
  pageRef = '/features'
  weight = 20

  [[menus.main]]
  name = 'Table of Contents'
  pageRef = '/tableofcontents'
  weight = 30

  [[menus.main]]
  name = 'Configuring the theme'
  pageRef = '/configuration'
  weight = 40

  [[menus.footer1]]
    name = 'Link 1'
    url = 'https://example.com'    
    [menus.footer1.params]
      rel = 'external'

  [[menus.footer4]]
    name = 'Link 1'
    url = 'https://example.com'    
    [menus.footer4.params]
      rel = 'external'

  [[menus.footer4]]
    name = 'Link 2'
    url = 'https://example.com'    
    [menus.footer4.params]
      rel = 'external'

[module]
  [module.hugoVersion]
    extended = true
    min = "0.146.0"
