baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'My New Hugo Site'

theme = 'hugo-theme-janssen-2'
themesDir = '../..'

sectionPagesMenu = 'main'

[params]
  copyright = "Copyright &copy; 2025 This Person, Inc."
  footer1_title = "Footer 1"
  footer2_title = "Footer 2"
  footer3_title = "Footer 3"
  footer4_title = "Footer 4"

[menus]
  [[menus.main]]
  name = 'Getting started'
  pageRef = '/getting-started'
  weight = 1
  
  [[menus.main]]
  name = 'Features'
  pageRef = '/features'
  weight = 12

  [[menus.footer1]]
    name = 'Link 1'
    url = 'https://example.com'    
    [menus.footer1.params]
      rel = 'external'

  [[menus.footer4]]
    name = 'Link 1'
    url = 'https://example.com'    
    [menus.footer4.params]
      rel = 'external'

  [[menus.footer4]]
    name = 'Link 2'
    url = 'https://example.com'    
    [menus.footer4.params]
      rel = 'external'

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
