baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Janssen'

theme = 'hugo-theme-janssen'
themesDir = '../..'

[params]
  copyright = "Copyright &copy; 2025 This Person, Inc."
  footer1_title = "Learn"
  footer2_title = "Footer 2"
  footer3_title = "Footer 3"
  footer4_title = "Links"

[menus]
  [[menus.main]]
  name = 'Getting started'
  pageRef = '/getting-started'
  weight = 1
  
  [[menus.main]]
  name = 'Features'
  pageRef = '/features'
  weight = 20

  [[menus.main]]
  name = 'Table of Contents'
  pageRef = '/tableofcontents'
  weight = 30

  [[menus.main]]
  name = 'Configuring the theme'
  pageRef = '/configuration'
  weight = 40

  [[menus.footer1]]
    name = 'Learn'
  
  [[menus.footer1]]
    parent = 'Learn'
    name = 'Getting started'
    pageRef = '/getting-started'
    weight = 1

  [[menus.footer1]]
    parent = 'Learn'
    name = 'Features'
    pageRef = '/features'
    weight = 2

  [[menus.footer1]]
    parent = 'Learn'
    name = 'Configuration'
    pageRef = '/configuration'
    weight = 3

  [[menus.footer4]]
    name = 'Links'

  [[menus.footer4]]
    parent = 'Links'
    name = 'GitHub'
    url = 'https://github.com/jwtay1/hugo-theme-janssen'    

[module]
  [module.hugoVersion]
    extended = true
    min = "0.146.0"
